services:
  - type: web
    name: nekxuz-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BUILD_TIMESTAMP
        value: "1772911920"
