services:
  - type: web
    name: nekxuz-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: NODE_VERSION
        value: "20"
